[package]
name = "crankshaft-config"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
config = "0.14.0"
dirs.workspace = true
regex.workspace = true
serde.workspace = true
url.workspace = true

[lints]
workspace = true
